### ISSUE TITLE
cmd run dense_flow.exe error

### ISSUE THREAD

**Issue by Heisenberg-C** [wanglimin/dense_flow#13]
Hi, thanks for your first.

After using cmake to build a solution and using Visual Studio 2015 to build a dense_flow.exe, when I use cmd to run the dense_flow.exe, it crushes as this:

![112](https://user-images.githubusercontent.com/24985018/28860958-54c7466a-7791-11e7-92ef-429b31573696.JPG)

Could you please help me?

**Comment by 07wlm** [comment]
I did not try this code in the window OS. It seems that it fails to parse input argument. It should be a common error for OpenCV and you could find solution from following link:

http://answers.opencv.org/question/90232/commandlineparser-only-gets-true/

**Comment by Heisenberg-C** [comment]
![image](https://user-images.githubusercontent.com/24985018/28903145-e306f3ea-7835-11e7-9235-cf41264dbb57.png)

Hi,  thx for your reply.
I used VS2015 to debug and I found there is a interrupt in the class CommandlineParser.
The function is about getting the name of string. The interrupt just happens at the return value.
Could you please give me more advice?

**Comment by wanglimin** [comment]
Did you try the solution from the link I provide?

**Comment by Heisenberg-C** [comment]
Yes, but it didn't work. 
I have tried to not use the const char* keys and cmd,  but to define these variables directly and set their directory in the dense_flow cpp file.
It worked and generated optical flow pictures.
