### ISSUE TITLE
question about extract optical flow

### ISSUE THREAD

**Issue by sophiazy** [wanglimin/dense_flow#17]
Hi@wanglimin :

when I run the"cmake CMakeLists.txt"and"make" in linux terminal,The generating execute file is  "denseImage",when I execute the "denseImage",only gengerate the RGB file, can not generate flow file,
in the "CMakeLists.txt" file,only include "denseImage.cpp",not include"denseFlow_gpu.cpp",
so I doubt that it need to modify the "CMakeLists.txt",I really appreciate for your reply.

Thanks in advance!

**Comment by wanglimin** [comment]
Yes, you need to modify the CMakeLists.txt to build denseFlow_gpu.cpp.

**Comment by sophiazy** [comment]
Thanks for your reply,Could you please tell me how to modify the  CMakeLists.txt? I can not modify the file correctly.

**Comment by bucktoothsir** [comment]
@sophiazy 
```
cmake_minimum_required(VERSION 2.8)
project( denseFlow )
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( denseFlow_gpu denseFlow_gpu.cpp )
target_link_libraries( denseFlow_gpu ${OpenCV_LIBS} )
```
