### ISSUE TITLE
dense_flow

### ISSUE THREAD

**Issue by Jangol** [wanglimin/dense_flow#2]
@wanglimin 

这个工具必须要有GPU才能运行吗？只有CPU怎么用呢？

**Comment by wanglimin** [comment]
The following code is based on CPU:

https://github.com/wanglimin/dense_flow/blob/master/denseFlow.cpp

You should try to compile it by yourself.

**Comment by Jangol** [comment]
@wanglimin 
Thank you very much, I solved this problem.
