### ISSUE TITLE
bash: ./denseFlow_gpu: No such file or directory

### ISSUE THREAD

**Issue by milkcat0904** [wanglimin/dense_flow#20]
hi，i don't know how to run the code,
i have cmake the CMakeLists.txt and make it 
$ cmake CMakeLists.txt 

$ make

then,i run the cmd:
$ ./denseFlow_gpu -f test.avi -x tmp/flow_x -y tmp/flow_x -i tmp/image -b 20 -t 1 -d 0 -s 1
bash: ./denseFlow_gpu: No such file or directory

could u plz tell me how to fix it?

**Comment by wanglimin** [comment]
The CMakeLists.txt is for denseImage. If you need to compile denseFlow, please change CMakeLists.txt as:

cmake_minimum_required(VERSION 2.8)
project( denseFlow )
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( denseFlow_gpu denseFlow_gpu.cpp )
target_link_libraries( denseFlow_gpu ${OpenCV_LIBS} )

**Comment by milkcat0904** [comment]
Thanks a lot！It works.
but the tmp file only get flow_x images and  frames images 
and the terminal shows that
$ ./denseFlow_gpu -f test.avi -x tmp/flow_x -y tmp/flow_x -i tmp/image -b 20 -t 1 -d 0 -s 1
                    
[mpeg4 @ 0x255fd80] too many thread_release_buffer calls!

**Comment by milkcat0904** [comment]
hey,i changed the cmd:
$ ./denseFlow_gpu -f test.avi -x tmp/flow_x -y tmp/flow_x -i tmp/image -b 20 -t 1 -d 0 -s 1
into:
$ ./denseFlow_gpu -f test.avi -x tmp/flow_x -y tmp/flow_y -i tmp/image -b 20 -t 1 -d 0 -s 1
then i got flow_y images 
thx a lot!
