### ISSUE TITLE
error after make

### ISSUE THREAD

**Issue by Zhuysheng** [wanglimin/dense_flow#21]
after make,i meet this problem:

/home/dense_flow-master/denseFlow_gpu.cpp: In function ‘int main(int, char**)’:
/home/dense_flow-master/denseFlow_gpu.cpp:71:2: error: reference to ‘FarnebackOpticalFlow’ is ambiguous
  FarnebackOpticalFlow alg_farn;
  ^
In file included from /home/dense_flow-master/denseFlow_gpu.cpp:4:0:
/usr/include/opencv2/gpu/gpu.hpp:1847:18: note: candidates are: class cv::gpu::FarnebackOpticalFlow
 class CV_EXPORTS FarnebackOpticalFlow
                  ^
In file included from /home/dense_flow-master/denseFlow_gpu.cpp:1:0:
/usr/local/include/opencv2/video/tracking.hpp:551:20: note:                 class cv::FarnebackOpticalFlow
 class CV_EXPORTS_W FarnebackOpticalFlow : public DenseOpticalFlow
                    ^
/home/dense_flow-master/denseFlow_gpu.cpp:71:23: error: expected ‘;’ before ‘alg_farn’
  FarnebackOpticalFlow alg_farn;
                       ^
/home/dense_flow-master/denseFlow_gpu.cpp:111:42: error: ‘alg_farn’ was not declared in this scope
    alg_farn(frame_0,frame_1,flow_u,flow_v);
                                          ^
make[2]: *** [CMakeFiles/denseFlow_gpu.dir/denseFlow_gpu.cpp.o] Error 1
make[1]: *** [CMakeFiles/denseFlow_gpu.dir/all] Error 2
make: *** [all] Error 2

how to fix it

**Comment by wanglimin** [comment]
Which version of OpenCV do you use? We test our code on Opencv 2.4.12.

**Comment by Zhuysheng** [comment]
thank you ,i try opencv2,4, it works
