### ISSUE TITLE
fatal error: opencv2/gpu/gpu.hpp: No such file or directory

### ISSUE THREAD

**Issue by VinACE** [wanglimin/dense_flow#24]
(cv) vinsent_research@instance-group-1-3p16:~/dense_flow$ sudo make 
Scanning dependencies of target denseFlow_gpu
[ 50%] Building CXX object CMakeFiles/denseFlow_gpu.dir/denseFlow_gpu.cpp.o
/home/vinsent_research/dense_flow/denseFlow_gpu.cpp:4:31: fatal error: opencv2/gpu/gpu.hpp: No such file or directory
compilation terminated.
CMakeFiles/denseFlow_gpu.dir/build.make:62: recipe for target 'CMakeFiles/denseFlow_gpu.dir/denseFlow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseFlow_gpu.dir/denseFlow_gpu.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/denseFlow_gpu.dir/all' failed
make[1]: *** [CMakeFiles/denseFlow_gpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have installed all the necessary packages by following 
https://github.com/VinACE/Install-TensorFlow-OpenCV-GPU-Ubuntu-17.10 
my opencv 3.4.1  install in ubutu 18

sudo cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/usr/local \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D INSTALL_C_EXAMPLES=OFF \
	-DPYTHON2_EXECUTABLE=/usr/bin/python2 \
	-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.4.1/modules \
	-D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
	-D WITH_CUDA=ON \
	-D CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-5 \
    -D CMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-5 \
	-D BUILD_EXAMPLES=ON ..

**Comment by wanglimin** [comment]
This code is for opencv2.4 and ubuntu 14.04.
