### ISSUE TITLE
CMakeFiles/extract_cpu.dir/build.make:120: recipe for target 'extract_cpu' failed

### ISSUE THREAD

**Issue by Infinite-Song** [wanglimin/dense_flow#27]
[ 71%] Linking CXX executable extract_warp_gpu
/usr/bin/ld: cannot find -lopencv_dep_cudart
/usr/bin/ld: cannot find -lopencv_dep_nppial
/usr/bin/ld: cannot find -lopencv_dep_nppicc
/usr/bin/ld: cannot find -lopencv_dep_nppicom
/usr/bin/ld: cannot find -lopencv_dep_nppidei
/usr/bin/ld: cannot find -lopencv_dep_nppif
/usr/bin/ld: cannot find -lopencv_dep_nppig
/usr/bin/ld: cannot find -lopencv_dep_nppim
/usr/bin/ld: cannot find -lopencv_dep_nppist
/usr/bin/ld: cannot find -lopencv_dep_nppisu
/usr/bin/ld: cannot find -lopencv_dep_nppitc
collect2: error: ld returned 1 exit status
CMakeFiles/extract_cpu.dir/build.make:120: recipe for target 'extract_cpu' failed
make[2]: *** [extract_cpu] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/extract_cpu.dir/all' failed

Hi, when I use the cammand make -j, it  shows a problem like this ! Can anyone give me some suggestions? Thanks!

**Comment by wanglimin** [comment]
This is the issue of opencv itself:

https://github.com/opencv/opencv/issues/6542
