### ISSUE TITLE
can I extract rgb and optical images use fps=25?

### ISSUE THREAD

**Issue by lwq1122** [wanglimin/dense_flow#28]
Hi, your work is very helpful to me! thank you
but I found it extract flow images use fps=30, please tell me how can i set fps=25 and use this to extract optical flow images?

**Comment by wanglimin** [comment]
This code is for optical flow extraction and cannot change the FPS of video.

**Comment by lwq1122** [comment]
> This code is for optical flow extraction and cannot change the FPS of video.
Thank you
