### ISSUE TITLE
why is the TVL1 with GPU so slow?

### ISSUE THREAD

**Issue by ahwangyuwei** [wanglimin/dense_flow#29]
I ran the algorithm on two GPUs and 8 workers, but the consumed 10 hours for 1000 videos (5~15 seconds duration per video) .
Anyone know why is so slow ?
Thanks.

**Comment by zhangluustb** [comment]
I ran the algorithm on two 1080ti and 8 workers and step=3,ucf101 dataset consumed 28hours for 13K videos.
