### ISSUE TITLE
Errors make denseFlow_gpu

### ISSUE THREAD

**Issue by Chuseuiti** [wanglimin/dense_flow#3]
After make I get the following errors:

/usr/include/opencv2/gpu/gpu.hpp:432:29: error 'vector' does not name a type

/denseFlow_gpu.cpp: In function 'int main(int, char**)':
/denseFlow_gpu.cpp:51:2: error: 'string' was not declared in this scope

/denseFlow_gpu.cpp:60:23: error: ‘vidFile’ was not declared in this scope

CMakeFiles/denseFlow_gpu.dir/build.make:54: recipe for target 'CMakeFiles/denseFlow_gpu.dir/denseFlow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseFlow_gpu.dir/denseFlow_gpu.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/denseFlow_gpu.dir/all' failed
make[1]: *** [CMakeFiles/denseFlow_gpu.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wanglimin** [comment]
What is your opencv version and how do you compile denseFlow_gpu.cpp?

**Comment by Chuseuiti** [comment]
Hi, 

My opencv version is 3.0.0 and by typping in the dense_flow folder:

cmake CMakeLists.txt

make

**Comment by wanglimin** [comment]
Our code is compatible with opencv 2.4.8. Perhaps, you need to try this version.
