### ISSUE TITLE
/usr/bin/ld: cannot find -lopencv_dep_cudart

### ISSUE THREAD

**Issue by MaAo** [wanglimin/dense_flow#30]
Hi, I use CentOS 7 and opencv-2.4.13.
When I run "make" ,I got this--

[maao@f5c93f0bb4ed build]$ make 
Scanning dependencies of target denseFlow_gpu
[ 50%] Building CXX object CMakeFiles/denseFlow_gpu.dir/denseFlow_gpu.cpp.o
[100%] Linking CXX executable denseFlow_gpu
/usr/bin/ld: cannot find -lopencv_dep_cudart
/usr/bin/ld: cannot find -lopencv_dep_nppial
/usr/bin/ld: cannot find -lopencv_dep_nppicc
/usr/bin/ld: cannot find -lopencv_dep_nppicom
/usr/bin/ld: cannot find -lopencv_dep_nppidei
/usr/bin/ld: cannot find -lopencv_dep_nppif
/usr/bin/ld: cannot find -lopencv_dep_nppig
/usr/bin/ld: cannot find -lopencv_dep_nppim
/usr/bin/ld: cannot find -lopencv_dep_nppist
/usr/bin/ld: cannot find -lopencv_dep_nppisu
/usr/bin/ld: cannot find -lopencv_dep_nppitc
collect2: error: ld returned 1 exit status
make[2]: *** [denseFlow_gpu] Error 1
make[1]: *** [CMakeFiles/denseFlow_gpu.dir/all] Error 2
make: *** [all] Error 2

Can you help me feed this?
Very thanks!

**Comment by wanglimin** [comment]
I think this is the issue of opencv itself. Please check:

https://github.com/opencv/opencv/issues/6542
