### ISSUE TITLE
.mkv video file input acceptable or not?

### ISSUE THREAD

**Issue by chubchubcharles** [wanglimin/dense_flow#4]
I typed in the command suggested in the README, but using a .mkv video file instead of a .avi file.
Not surprisingly, I received error messages:

$ ./denseFlow_gpu -f sample_video_file.mkv -x ./tmp/flow_x/ -y ./tmp/flow_y -i ./tmp/images -b 20 -t 1 -d 0 -s 1
[h264 @ 0x899740] AVC: nal size 75
[h264 @ 0x899740] missing picture in access unit with size 75
[h264 @ 0xb24960] AVC: nal size 75
[h264 @ 0xb24960] AVC: nal size 75
[h264 @ 0xb24960] no frame!
[h264 @ 0x899740] AVC: nal size 75
[h264 @ 0x899740] missing picture in access unit with size 75
[h264 @ 0x951660] AVC: nal size 75
[h264 @ 0x951660] AVC: nal size 75
[h264 @ 0x951660] no frame!
....

However, surprisingly, I successfully obtained the .jpg files for both key frames and optical flow frames.
My main question is what are these error messages and should they be of concern?
Does the script accept .mkv file format?

**Comment by wanglimin** [comment]
Hi, I did not try the format of mkv before. I think it should be the problem of decoding. You can refer to opencv doc to check they can deal with mkv format.

**Comment by chubchubcharles** [comment]
According to OpenCV docs found [here](http://docs.opencv.org/2.4/doc/tutorials/highgui/video-write/video-write.html), "OpenCV for video containers supports only the avi extension."
Thanks for the help.
