### ISSUE TITLE
dense_flow_gpu.cpp error

### ISSUE THREAD

**Issue by SKBai1996** [wanglimin/dense_flow#40]
when I finished cmake .. ,I used the command "make", when it was in 81%，there is an issue.
[ 81%] Linking CXX executable extract_gpu
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, int, int)':
dense_flow_gpu.cpp:(.text+0x82b): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_flow_gpu.cpp:(.text+0x8a0): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_flow_gpu.cpp:(.text+0x8ef): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_flow_gpu.cpp:(.text+0x12eb): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowPureGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_flow_gpu.cpp:(.text+0x1b61): undefined reference to `cv::cudacodec::createVideoReader(cv::String const&)'
dense_flow_gpu.cpp:(.text+0x1c8e): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
dense_flow_gpu.cpp:(.text+0x1d03): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)'
dense_flow_gpu.cpp:(.text+0x1d52): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
dense_flow_gpu.cpp:(.text+0x258d): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
collect2: error: ld returned 1 exit status
CMakeFiles/extract_gpu.dir/build.make:143: recipe for target 'extract_gpu' failed
make[2]: *** [extract_gpu] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
My opencv version is 3.4.6,and cmake version is 3.5.1. My operation system is ubuntu16.04.
Could you help me.

**Comment by SKBai1996** [comment]
This is the problem of my own download opencv, the dense flow needs cuda module, but I didn't have it. So I reinstalled the opencv, and in cmake, I use the command as follow:
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=ON -D WITH_CUBLAS=ON -D BUILD_TIFF=ON -D WITH_CUDA=ON -D WITH_CUFFT=ON WITH_NVCUVID=ON -D OPENCV_EXTRA_MODULES_PATH=./opencv-3.4.6/opencv_contrib/modules ..
The other commands as usual, I sincerely can give someone else help.

**Comment by erhsh** [comment]
> when I finished cmake .. ,I used the command "make", when it was in 81%，there is an issue.
> [ 81%] Linking CXX executable extract_gpu
> libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, int, int)': dense_flow_gpu.cpp:(.text+0x82b): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
> dense_flow_gpu.cpp:(.text+0x8a0): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)' dense_flow_gpu.cpp:(.text+0x8ef): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
> dense_flow_gpu.cpp:(.text+0x12eb): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)' libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowPureGPU(std::__cxx11::basic_string<char, std::char_traits, std::allocator >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator >, std::allocator<std::vector<unsigned char, std::allocator > > >&, std::vector<std::vector<unsigned char, std::allocator >, std::allocator<std::vector<unsigned char, std::allocator > > >&, std::vector<std::vector<unsigned char, std::allocator >, std::allocator<std::vector<unsigned char, std::allocator > > >&)':
> dense_flow_gpu.cpp:(.text+0x1b61): undefined reference to `cv::cudacodec::createVideoReader(cv::String const&)' dense_flow_gpu.cpp:(.text+0x1c8e): undefined reference to `cv::cuda::FarnebackOpticalFlow::create(int, double, bool, int, int, int, double, int)'
> dense_flow_gpu.cpp:(.text+0x1d03): undefined reference to `cv::cuda::OpticalFlowDual_TVL1::create(double, double, double, int, int, double, int, double, double, bool)' dense_flow_gpu.cpp:(.text+0x1d52): undefined reference to `cv::cuda::BroxOpticalFlow::create(double, double, double, int, int, int)'
> dense_flow_gpu.cpp:(.text+0x258d): undefined reference to `cv::cuda::split(cv::_InputArray const&, cv::cuda::GpuMat*, cv::cuda::Stream&)'
> collect2: error: ld returned 1 exit status
> CMakeFiles/extract_gpu.dir/build.make:143: recipe for target 'extract_gpu' failed
> make[2]: *** [extract_gpu] Error 1
> CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
> make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> My opencv version is 3.4.6,and cmake version is 3.5.1. My operation system is ubuntu16.04.
> Could you help me.

same question with you，how do you resolve it？Hope got your help， Thanks
