### ISSUE TITLE
would you update the gpu denseflow to be opencv3.0.0 compatible?

### ISSUE THREAD

**Issue by nhe150** [wanglimin/dense_flow#5]

**Comment by wanglimin** [comment]
@nhe150 
Recently, I am a bit busy. Maybe, I will update my code to be compatible with OpenCV 3.0.

**Comment by nhe150** [comment]
works on opencv2.4.10

**Comment by divamgupta** [comment]
Check this out!
https://github.com/agethen/dense-flow

**Comment by qijiezhao** [comment]
I provide a py-denseflow version, which is easy to implement
