### ISSUE TITLE
Optical flow images using CPU and using GPU difference

### ISSUE THREAD

**Issue by ae86208** [wanglimin/dense_flow#7]
What's the major difference between optical flow images extracted using CPU and those using GPU?
Do the results differ a lot?

**Comment by wanglimin** [comment]
GPU and CPU implement the same optical flow algorithms, but GPU is much faster. In current version, three optical flow algorithms are implemented by GPU, including Brox, TVL1, Farneback. But only one optical flow algorithm (Farneback) is implemented by CPU. The results of different optical flow algorithms may have some differences.
