### ISSUE TITLE
I couldn't find frames

### ISSUE THREAD

**Issue by StOnEGiggity** [wanglimin/dense_flow#8]
Hello,When I am running ./denseImage,everything is ok until executing the code "capture>>frame",it looks like that there is no frame and then break.By the way ,test.avi could be open correctly.Somebody could help me?

**Comment by wanglimin** [comment]
I think it may be the problem of video decoding.

**Comment by StOnEGiggity** [comment]
Thanks for replying.Finally,i choose ffmpeg to extract frames.Maybe you could close the issue:)
