### ISSUE TITLE
能再详细点吗

### ISSUE THREAD

**Issue by double-vane** [wanglimin/dense_flow#9]
my English is so poor， can you detail a little? 
I don't know what to do after when I download your code
thank you

**Comment by wanglimin** [comment]
First, you need to use cmake to generate the Makefile. Then, you can use make command to compile and build the code.

**Comment by double-vane** [comment]
Linux?  I use the windows system

**Comment by wanglimin** [comment]
Yes, I used ubuntu 14.04.

**Comment by double-vane** [comment]
Thank you very much for reply，I'll download a cmake software first.. my English can't support the conversation with you. I am ashamed.

**Comment by double-vane** [comment]
![image](https://cloud.githubusercontent.com/assets/20334378/17969226/a1333b3a-6b03-11e6-9258-8857d378b52c.png) This is the result that I got,then what should I do

**Comment by wanglimin** [comment]
I did not try this code on window with visual studio. I suggest you to use Linux OS.

**Comment by double-vane** [comment]
Thank you very much

**Comment by double-vane** [comment]
Thank you all the same!  I solve the problem. I successfully ran the code

**Comment by sudonto** [comment]
Hi @double-vane, you ran on Windows? What Windows version?

**Comment by WhoSJackie** [comment]
how to run on windows please tell me
